apiVersion: apps/v1
kind: Deployment
metadata:
  name: gp-deployment
  labels:
    app: gp
spec:
  selector:
    matchLabels:
      app: gp
  replicas: 1
  template:
    metadata:
      labels:
        app: gp
    spec:
      imagePullSecrets:
        - name: dockerregistrykey
      containers:
        - name: gp
          image: {{ .Values.registry }}:{{ .Values.tag }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4001