name: Docker Publish

on:
  push:
    branches: [ main ]
  release:
    type: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Change directory to gradle-parser project
        run: |
          pwd
          cd gradle-parser
          ls -R
          chmod +x gradlew
          ./gradlew build
          cd ..
      - name: List dir
        run: |
          pwd
          ls -lah
      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
          image: micky0000/seclens
          registry: docker.io
          dockerfile: docker/DockerfileGithubAction
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
