name: KTlint Formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ktlint:
   runs-on: ubuntu-latest
  
   steps:
     - name: "checkout"
       uses: actions/checkout@v2
  
     - name: "ktlint"
       uses: "block42-blockchain-company/ktlint-action@master"
